log:
  disable_sentry: true

db:
  url: postgres://...@.../...?sslmode=disable

listener:
  addr: :8080

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: EtherUSDC
  service_port: 80

eth:
  eth_rpc: "your eth rpc values here" 
  eth_contract_address: "your eth contract address here"
  eth_block: "your number of the starting block to be processed"
