version: '3.9'

services:

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB: ${POSTGRES_DATABASE}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  service:
    image: registry.https://github.com/zepif/EtherUSDC
    environment:
      KV_VIPER_FILE: ./config.yaml
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DATABASE}?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./config.yaml:./config.yaml

  nginx:
    image: nginx:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:80"   # http
      - "8443:443"  # https
    volumes:
      - ./nginx.conf:./nginx.conf
    depends_on:
      - service

volumes:
  db-data:
