# version: '3.9'
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: on-failure

  service:
    build: .
    environment:
      KV_VIPER_FILE: ./config.local.yaml
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DATABASE}?sslmode=disable
    depends_on:
      - db
    volumes:
      - /home/acer/go/src/gitlab.com/zepif/EtherUSDC/config.local.yaml:/config.local.yaml
    command: /bin/sh -c "usr/local/bin/start.sh"
    restart: on-failure

  nginx:
    image: nginx:1.23.1
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:80"   # http
      - "8443:443"  # https
    volumes:
      - /home/acer/go/src/gitlab.com/zepif/EtherUSDC/nginx.conf:/nginx.conf
    depends_on:
      - service

volumes:
  db-data:

networks:
  default:
    driver: bridge
